name: remote ssh command
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_VPS }}
          username: ${{ secrets.USERNAME_VPS }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            ls al
            cd /www/wwwroot/laravel10.rentcarindo.com/
            git pull origin
            npm install
            npm run build
